version: '3'

tasks:
  activate-pyenv:
    cmds:
      - pyenv activate streamlit-bedrock
  run-streamlit:
    cmds:
      - streamlit run run-foundational-models.py
  open-analytics:
    cmds:
      - open http://localhost:8502/?analytics=on